//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GridMvcPOC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOpcode
    {
        public long OpcodeID { get; set; }
        public string OpcodeName { get; set; }
        public string OpcodeDescription { get; set; }
        public string ProgramID { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public bool IsActive { get; set; }
    }
}
